/*
 * Cliente.java
 *
 * Created on 22 de Outubro de 2005, 17:19
 */

package simulacao;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
* This code was generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* *************************************
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED
* for this machine, so Jigloo or this code cannot be used legally
* for any corporate or commercial purpose.
* *************************************
*/
/**
 *
 * @author  John Holiver
 */
public class Cliente extends javax.swing.JFrame {
    private ThreadCliente thread;
    
    /** Creates new form Cliente */
    public Cliente() {
        initComponents();
        this.setSize(242, 327);
        jComboBoxCarga.addItem("50/50");
        jComboBoxCarga.addItem("75/25");
        jComboBoxCarga.addItem("90/10");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButtonEnviarMsg = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldWaitTime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMsgTrans = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPorta = new javax.swing.JTextField();
        jComboBoxCarga = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");
        setBackground(new java.awt.Color(255, 255, 255));
        this.setResizable(false);
        jButtonEnviarMsg.setText("Iniciar");
        jButtonEnviarMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarMsgActionPerformed(evt);
            }
        });

        getContentPane().add(jButtonEnviarMsg);
        jButtonEnviarMsg.setBounds(29, 259, 160, 23);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 14));
        jLabel1.setText("Cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(78, 10, 60, 17);
        jLabel1.setForeground(new java.awt.Color(181,37,37));

        getContentPane().add(jTextFieldWaitTime);
        jTextFieldWaitTime.setBounds(183, 31, 20, 20);
        jTextFieldWaitTime.setText("5");

        jLabel2.setText("Wait Time (s)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(16, 36, 107, 15);

        getContentPane().add(jTextFieldIp);
        jTextFieldIp.setBounds(17, 163, 110, 20);
        jTextFieldIp.setText("127.0.0.1");

        jLabel3.setText("Ip do Srv / Porta");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(16, 139, 140, 15);
        jLabel3.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jTextFieldMsgTrans);
        jTextFieldMsgTrans.setBounds(183, 66, 20, 20);
        jTextFieldMsgTrans.setText("10");

        jLabel4.setText("Qtd max de Msgs/Trans");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(16, 70, 158, 15);

        getContentPane().add(jTextFieldPorta);
        jTextFieldPorta.setBounds(134, 162, 40, 20);
        jTextFieldPorta.setText("4321");

        getContentPane().add(jComboBoxCarga);
        jComboBoxCarga.setBounds(133, 108, 70, 19);

        jLabel5.setText("Carga R/W");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(16, 105, 87, 15);
		{
			jButtonConectar = new JButton();
			this.getContentPane().add(jButtonConectar);
			jButtonConectar.setText("conectar");
			jButtonConectar.setBounds(63, 189, 91, 21);
			jButtonConectar.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent evt) {
					jButtonConectarActionPerformed(evt);
				}
			});
		}
		{
			jTextFieldMensagem = new JTextField();
			this.getContentPane().add(jTextFieldMensagem);
			jTextFieldMensagem.setText("<START>");
			jTextFieldMensagem.setBounds(10, 225, 133, 17);
		}
		{
			jButtonEnviar = new JButton();
			this.getContentPane().add(jButtonEnviar);
			jButtonEnviar.setText("Enviar");
			jButtonEnviar.setBounds(151, 223, 78, 19);
			jButtonEnviar.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent evt) {
					jButtonEnviarActionPerformed(evt);
				}
			});
		}

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    private void jButtonEnviarMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarMsgActionPerformed
    	
        if(jButtonEnviarMsg.isSelected()){ //O envio de mensagens sera ligado
            jButtonEnviarMsg.setText("Parar");
            //Iniciar thread de envio!
            int qtdMsgTrans = Integer.parseInt(jTextFieldMsgTrans.getText());
            int waitTime = Integer.parseInt(jTextFieldWaitTime.getText());
            int tipoCarga = jComboBoxCarga.getSelectedIndex();
            int rollbackChance = 0;
            String ip = jTextFieldIp.getText();
            int porta = Integer.parseInt(jTextFieldPorta.getText());
            thread = new ThreadCliente(qtdMsgTrans, waitTime, tipoCarga, rollbackChance, ip, porta);
            thread.start();
        } else { //O envio de mensagens sera desligado
            jButtonEnviarMsg.setText("Iniciar");
            //Parar thread!
            thread.interrupt();
        }
    }//GEN-LAST:event_jButtonEnviarMsgActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }
    
	private void jButtonConectarActionPerformed(ActionEvent evt) {
		String ip = jTextFieldIp.getText();
        int porta = Integer.parseInt(jTextFieldPorta.getText());
    	thread = new ThreadCliente(0, 0, 0, 0, ip, porta);
    	thread.conectar();
	}
	
	private void jButtonEnviarActionPerformed(ActionEvent evt) {
		thread.enviaMensagem(jTextFieldMensagem.getText());
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jButtonEnviarMsg;
    private javax.swing.JComboBox jComboBoxCarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private JButton jButtonEnviar;
    private JTextField jTextFieldMensagem;
    private JButton jButtonConectar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldIp;
    private javax.swing.JTextField jTextFieldMsgTrans;
    private javax.swing.JTextField jTextFieldPorta;
    private javax.swing.JTextField jTextFieldWaitTime;
    // End of variables declaration//GEN-END:variables
    
}

